### ISSUE TITLE
Remove ImageOptim will avoid complex dependencys

### ISSUE THREAD

**Issue by huacnlee** [ksz2k/letter_avatar#1]
I saw the main feature just execute ImageMagick `convert` to generate image.

But in README file you said:

```
sudo apt-get install -y advancecomp gifsicle jhead jpegoptim libjpeg-progs optipng pngcrush pngquant
```

The install way looks like tooooo hard. 

If you remove ImageOptim, it will easily.

**Comment by ksz2k** [comment]
closing, thanks again :-) :+1:

**Comment by huacnlee** [comment]
😀

## 

Jason Lee

在 2015年10月28日 星期三，15:32，Krzysiek Szczuka 写道：

**Comment by huacnlee** [comment]
And I use this gem in production:

https://ruby-china.org/topics/last  

## 

Jason Lee

在 2015年10月28日 星期三，15:33，Jason Lee 写道：

**Comment by ksz2k** [comment]
Wow, nice to know.. I'ts probably the biggest site using our gem :sunglasses: 

PS I've just pushed new version (`v0.0.9`) to rubygems.org
