### ISSUE TITLE
include Letter::Avatar Throwing Uninitialized Constant Error

### ISSUE THREAD

**Issue by Nerdenberger** [ksz2k/letter_avatar#14]
Howdy
I am using Rails 5.0.4

`LetterAvatar.generate 'ksz2k', 200` is working just fine.  (This is what I get in the rails console)

```
[2] pry(main)> LetterAvatar.generate 'ksz2k', 200
=> "public/system/lets/letter_avatars/2/K/87_178_230/200.png"
```

However when trying to use the HasAvatar helper I get the following error
```
[4] pry(main)> LetterAvatar::HasAvatar
NameError: uninitialized constant LetterAvatar::HasAvatar
```

Any ideas on what could be going on here?

**Comment by ksz2k** [comment]
you must `require` it

```ruby 
require "letter_avatar/has_avatar"
```

**Comment by ksz2k** [comment]
closing, hope it works now..
