### ISSUE TITLE
`LetterAvatar.resize` increased bytesize of avatar file under certain environment

### ISSUE THREAD

**Issue by snow** [ksz2k/letter_avatar#16]
with ImageMagick 6.8.9-9 Q16 x86_64 2017-07-31, ubuntu 16.04.3 LTS

https://github.com/ksz2k/letter_avatar/blob/3ae1ad90d749b1926f4e0bf5da9ec407859a77f5/lib/letter_avatar/avatar.rb#L64 generates fullsize (240px) files at around 5kb

but after https://github.com/ksz2k/letter_avatar/blob/3ae1ad90d749b1926f4e0bf5da9ec407859a77f5/lib/letter_avatar.rb#L19 I got files at aroud 50kb regardless value of pixel size.

with imagemagick: stable 7.0.7-28, macOS 10.13.3, `LetterAvatar.resize`d files reminded under 10kb.

So I think it may be an issue with ImageMagick.

I'm not very good at English so sorry if there are any English syntax error.

**Comment by snow** [comment]
But instead of diving into ImageMagick / ubuntu, I found patching `LetterAavatar::Avatar.generate`https://github.com/ksz2k/letter_avatar/blob/3ae1ad90d749b1926f4e0bf5da9ec407859a77f5/lib/letter_avatar/avatar.rb#L46
as:
```ruby
LetterAvatar.resize(fullsize, filename, size, size) if size != FULLSIZE
```
solved my problem much quicker (240px meets the needs of what I'm working on). And I think avoid resizing to same size makes sense. Should I create a PR of `if size != FULLSIZE`?

**Comment by ksz2k** [comment]
hi @snow thanks for finding this out, sure make a PR please :-)
