### ISSUE TITLE
Doesn't it support utf-8 character ？

### ISSUE THREAD

**Issue by songjiayang** [ksz2k/letter_avatar#3]
Hi @ksz2k, thanks for your share first.  when i try it , i meet a problem about  utf-8 character generating.

Test Case:  `LetterAvatar.generate "宋佳洋", 200`
Result:  ![40](https://cloud.githubusercontent.com/assets/1459834/11014113/c70bd064-8563-11e5-9c32-e361d877815c.png)

Does it really support or my ImageMagic version problem?

Version: ImageMagick 6.8.9-7

**Comment by huacnlee** [comment]
The default font not support Chineses
