### ISSUE TITLE
mattr_accessor is defined in ActiveSupport but the dependency is not stated

### ISSUE THREAD

**Issue by strzibny** [ksz2k/letter_avatar#7]
Since I would like to avoid the dependency on AS, let's rewrite the code to not depend on AS.

```
> require 'letter_avatar'
NoMethodError: undefined method `mattr_accessor' for LetterAvatar:Module
    from /home/vagrant/.gem/ruby/gems/letter_avatar-0.1.7/lib/letter_avatar.rb:7:in `<module:LetterAvatar>'
    from /home/vagrant/.gem/ruby/gems/letter_avatar-0.1.7/lib/letter_avatar.rb:5:in `<top (required)>'
    from (irb):2:in `require'
    from (irb):2
    from /usr/bin/irb:11:in `<main>'
```

**Comment by ksz2k** [comment]
done :-)

**Comment by ksz2k** [comment]
`Thread.current` used

**Comment by ksz2k** [comment]
as @huacnlee suggested, `Thread.current` is not the best idea, fixed in b5479e170d16d162162ca2a1c36f83ca3859deb1

**Comment by ksz2k** [comment]
@strzibny please confirm it's all work OK for you

from d53e4b1014efebcd5745e4466a5ca58eeb9b298d `letter_avatar_tag` does not require `ActionView::Helpers::AssetTagHelper` anymore

**Comment by ksz2k** [comment]
closing for now, let us know if anything is still wrong..

thanks again for suggestion!

**Comment by strzibny** [comment]
Sorry that I havent time to reply, thanks.
